services:
  oloy.email.repository:
    class: OpenLoyalty\Component\Email\Infrastructure\Persistence\Doctrine\Repository\DoctrineEmailRepository
    factory: ['@doctrine.orm.entity_manager', getRepository]
    arguments:
      - 'OpenLoyalty\Component\Email\Domain\Email'

  oloy.email.command_handler:
    class: OpenLoyalty\Component\Email\Domain\Command\EmailCommandHandler
    arguments:
      - '@oloy.email.repository'
      - '@broadway.event_dispatcher'
      - { from_name: '%mailer_from_name%', from_address: '%mailer_from_address%' }
    lazy: true
    tags:
      - { name: broadway.command_handler }

  oloy.email.read_model.repository:
    class: OpenLoyalty\Component\Email\Infrastructure\ReadModel\Doctrine\Repository\DoctrineEmailRepository
    arguments:
      - '@doctrine.dbal.default_connection'
