OpenLoyalty\Component\Campaign\Domain\CampaignCategory:
  properties:
    campaignCategoryId:
      expose: true
      inline: true
    newTranslations:
      exclude: true
    currentLocale:
      exclude: true
    defaultLocale:
      exclude: true
  virtual_properties:
    getName:
      serialized_name: name
