OpenLoyalty\Component\EarningRule\Domain\EarningRule:
  exlusion_policy: ALL
  discriminator:
    field_name: type
    map:
      points: OpenLoyalty\Component\EarningRule\Domain\PointsEarningRule
      event: OpenLoyalty\Component\EarningRule\Domain\EventEarningRule
      custom_event: OpenLoyalty\Component\EarningRule\Domain\CustomEventEarningRule
      product_purchase: OpenLoyalty\Component\EarningRule\Domain\ProductPurchaseEarningRule
      multiply_for_product: OpenLoyalty\Component\EarningRule\Domain\MultiplyPointsForProductEarningRule
      multiply_by_product_labels: OpenLoyalty\Component\EarningRule\Domain\MultiplyPointsByProductLabelsEarningRule
      referral: OpenLoyalty\Component\EarningRule\Domain\ReferralEarningRule
      instant_reward: OpenLoyalty\Component\EarningRule\Domain\InstantRewardRule
      geolocation: OpenLoyalty\Component\EarningRule\Domain\EarningRuleGeo
      qrcode: OpenLoyalty\Component\EarningRule\Domain\EarningRuleQrcode
  properties:
    earningRuleId:
      expose: true
      inline: true
    levels:
      exclude: true
    segments:
      exclude: true
    pos:
      exclude: true
    earningRulePhoto:
      exclude: true
  virtual_properties:
      getFlatLevels:
          serialized_name: levels
          type: array
      getFlatSegments:
          serialized_name: segments
          type: array
      getFlatPos:
          serialized_name: pos
          type: array
      hasEarningRulePhoto:
          serialized_name: hasPhoto
          type: boolean
