services:

  _defaults:
      autowire: true
      autoconfigure: true
      public: false

  OpenLoyalty\Component\MarkDown\Infrastructure\ParseDownParser: ~
  OpenLoyalty\Bundle\MarkDownBundle\Service\ContextMarkDownFormatter: ~
