change_password:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/ChangePasswordController.php'
    type: annotation

customer:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/CustomerController.php'
    type: annotation

customer_pushy:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/CustomerPushyController.php'
    type: annotation

seller:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/SellerController.php'
    type: annotation

security:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/SecurityController.php'
    type: annotation

customer_search:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/CustomerSearchController.php'
    type: annotation

password_reset:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/ResetPasswordController.php'
    type: annotation

admin:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/AdminController.php'
    type: annotation

invitation:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/InvitationController.php'
    type: annotation

acl:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/AclController.php'
    type: annotation

campaign_bought:
    resource: '@OpenLoyaltyUserBundle/Controller/Api/CampaignBoughtController.php'
    type: annotation
