services:
    _defaults:
        autowire: true

    oloy.user.customer.command_handler:
        class: OpenLoyalty\Component\Customer\Domain\Command\CustomerCommandHandler
        arguments:
            - '@oloy.user.customer.repository'
            - '@oloy.user.customer.unique_validator'
            - '@broadway.event_dispatcher'
            - '@oloy.audit.manager'
            - '@OpenLoyalty\Component\Customer\Infrastructure\LevelDowngradeModeProvider'
        lazy: true
        tags:
            - { name: broadway.command_handler }

    oloy.user.invitation.sha_token_generator:
        class: OpenLoyalty\Component\Customer\Domain\Service\ShaInvitationTokenGenerator
        public: false

    oloy.user.invitation.token_generator: '@oloy.user.invitation.sha_token_generator'

    oloy.user.invitation.command_handler:
        class: OpenLoyalty\Component\Customer\Domain\Command\InvitationCommandHandler
        arguments:
            - '@oloy.user.invitation.repository'
            - '@oloy.user.invitation.token_generator'
            - '@broadway.event_dispatcher'
        lazy: true
        tags:
            - { name: broadway.command_handler }

    oloy.user.seller.command_handler:
        class: OpenLoyalty\Component\Seller\Domain\Command\SellerCommandHandler
        arguments:
            - '@oloy.user.seller.repository'
            - '@oloy.user.seller.unique_validator'
        lazy: true
        tags:
            - { name: broadway.command_handler }

    oloy.user.customer.unique_validator:
        class: OpenLoyalty\Component\Customer\Domain\Validator\CustomerUniqueValidator
        arguments:
            - '@oloy.user.read_model.repository.customer_details'

    oloy.user.seller.unique_validator:
        class: OpenLoyalty\Component\Seller\Domain\Validator\SellerUniqueValidator
        arguments:
            - '@oloy.user.read_model.repository.seller_details'

    OpenLoyalty\Component\Customer\Domain\EventSourcedCustomerRepository:
        arguments:
            - '@broadway.event_store'
            - '@broadway.event_handling.event_bus'
            - ['@broadway.metadata_enriching_event_stream_decorator']

    OpenLoyalty\Component\Customer\Domain\CustomerRepository:
        arguments:
            - '@OpenLoyalty\Component\Customer\Domain\EventSourcedCustomerRepository'
            - '@broadway.event_store'
            - '@OpenLoyalty\Bundle\CoreBundle\Repository\DBALSnapshotRepository'
            - '@Broadway\Snapshotting\Snapshot\Trigger\EventCountTrigger'

    oloy.user.invitation.repository:
        class: OpenLoyalty\Component\Customer\Domain\InvitationRepository
        arguments:
            - '@broadway.event_store'
            - '@broadway.event_handling.event_bus'
            - ['@broadway.metadata_enriching_event_stream_decorator']

    oloy.user.seller.repository:
        class: OpenLoyalty\Component\Seller\Domain\SellerRepository
        arguments:
            - '@broadway.event_store'
            - '@broadway.event_handling.event_bus'
            - ['@broadway.metadata_enriching_event_stream_decorator']

    oloy.user.read_model.repository.customer_details:
        class: 'Broadway\ReadModel\ReadModel'
        factory: ['@oloy.read_model.repository.factory', create]
        arguments:
            - 'oloy.customer_details'
            - 'OpenLoyalty\Component\Customer\Domain\ReadModel\CustomerDetails'
            - 'OpenLoyalty\Component\Customer\Infrastructure\Repository\CustomerDetailsElasticsearchRepository'

    oloy.user.read_model.repository.invitation_details:
        class: 'Broadway\ReadModel\ReadModel'
        factory: ['@oloy.read_model.repository.factory', create]
        arguments:
            - 'oloy.invitation_details'
            - 'OpenLoyalty\Component\Customer\Domain\ReadModel\InvitationDetails'
            - 'OpenLoyalty\Component\Customer\Infrastructure\Repository\InvitationDetailsElasticsearchRepository'

    oloy.user.read_model.repository.seller_details:
        class: 'Broadway\ReadModel\ReadModel'
        factory: ['@oloy.read_model.repository.factory', create]
        arguments:
            - 'oloy.seller_details'
            - 'OpenLoyalty\Component\Seller\Domain\ReadModel\SellerDetails'
            - 'OpenLoyalty\Component\Seller\Infrastructure\Repository\SellerDetailsElasticsearchRepository'

    oloy.user.customer.read_model.projector.customer_details:
        class: 'OpenLoyalty\Component\Customer\Domain\ReadModel\CustomerDetailsProjector'
        tags:
            - { name: broadway.domain.event_listener }
        arguments:
            $repository: '@oloy.user.read_model.repository.customer_details'
            $customerAggregateRootRepository: '@oloy.user.customer.repository'
            $levelRepository: '@oloy.level.repository'
            $transactionRepository: '@oloy.transaction.repository'

    oloy.user.customer.read_model.projector.invitation_details:
        class: 'OpenLoyalty\Component\Customer\Domain\ReadModel\InvitationDetailsProjector'
        tags:
            - { name: broadway.domain.event_listener }
        arguments:
            - '@oloy.user.customer.repository'
            - '@oloy.user.read_model.repository.invitation_details'

    oloy.user.customer.read_model.projector.seller_details:
        class: 'OpenLoyalty\Component\Seller\Domain\ReadModel\SellerDetailsProjector'
        tags:
            - { name: broadway.domain.event_listener }
        arguments:
            - '@oloy.user.read_model.repository.seller_details'
            - '@oloy.pos.repository'

    oloy.user.read_model.repository.customers_belonging_to_one_level:
        class: 'Broadway\ReadModel\ReadModel'
        factory: ['@oloy.read_model.repository.factory', create]
        arguments:
            - 'oloy.customers_belonging_to_one_level'
            - 'OpenLoyalty\Component\Customer\Domain\ReadModel\CustomersBelongingToOneLevel'
            - 'OpenLoyalty\Component\Customer\Infrastructure\Repository\CustomersBelongingToOneLevelElasticsearchRepository'

    oloy.user.customer.read_model.projector.customers_belonging_to_one_level:
        class: 'OpenLoyalty\Component\Customer\Domain\ReadModel\CustomersBelongingToOneLevelProjector'
        tags:
            - { name: broadway.domain.event_listener }
        arguments:
            - '@oloy.user.customer.repository'
            - '@oloy.user.read_model.repository.customers_belonging_to_one_level'
            - '@oloy.level.repository'

    OpenLoyalty\Component\Customer\Infrastructure\LevelDowngradeModeProvider:
        alias: OpenLoyalty\Bundle\UserBundle\Service\SettingsBasedLevelDowngradeModeProvider

    OpenLoyalty\Bundle\UserBundle\Service\SettingsBasedLevelDowngradeModeProvider:
        autowire: true

    OpenLoyalty\Component\Customer\Infrastructure\SystemEvent\Listener\AssignTransactionToCustomerListener:
        tags:
            - { name: broadway.event_listener, event: oloy.transaction.customer_assigned, method: handle }

    OpenLoyalty\Component\Customer\Infrastructure\SystemEvent\Listener\AssignAccountToCustomerListener:
        tags:
            - { name: broadway.event_listener, event: oloy.account.created, method: handle }

    oloy.user.customer.listener.calculate_customer_level:
        class: 'OpenLoyalty\Component\Customer\Infrastructure\SystemEvent\Listener\CalculateCustomerLevelListener'
        lazy: true
        tags:
            - { name: broadway.event_listener, event: oloy.transaction.customer_assigned, method: handle }
            - { name: broadway.event_listener, event: oloy.account.created, method: handle }
            - { name: broadway.event_listener, event: oloy.account.available_points_amount_changed, method: handle }
            - { name: broadway.event_listener, event: oloy.customer.manually_level_removed, method: handle }
            - { name: broadway.event_listener, event: oloy.customer.recalculate_level_requested, method: handle }
        arguments:
            - '@oloy.user.level_id_provider'
            - '@oloy.user.read_model.repository.customer_details'
            - '@broadway.command_handling.command_bus'
            - '@oloy.user.tier_assign_type_provider'
            - '@oloy.user.exclude_delivery_costs_provider'
            - '@oloy.level.repository'
            - '@broadway.event_dispatcher'
            - '@oloy.customer_status_provider'
            - '@OpenLoyalty\Component\Customer\Infrastructure\LevelDowngradeModeProvider'
            - '@oloy.points.account.repository.account_details'

    oloy.user.customer.listener.create_account:
        class: 'OpenLoyalty\Component\Customer\Infrastructure\SystemEvent\Listener\CreateAccountListener'
        tags:
            - { name: broadway.event_listener, event: oloy.customer.registered, method: handleCustomerRegistered }
        arguments:
            - '@broadway.command_handling.command_bus'
            - '@broadway.uuid.generator'

    OpenLoyalty\Component\Customer\Infrastructure\SystemEvent\Listener\CreateCouponsReturnListener:
        arguments:
            $uuidGenerator: '@broadway.uuid.generator'
        lazy: true
        tags:
            - { name: broadway.event_listener, event: oloy.transaction.customer_assigned, method: handleCustomerAssignedToTransaction }

    oloy.user.seller.listener.pos_updated:
        class: 'OpenLoyalty\Component\Seller\Infrastructure\SystemEvent\Listener\UpdatePosDataListener'
        tags:
            - { name: broadway.event_listener, event: oloy.pos.updated, method: handlePosUpdated }
        arguments:
            - '@oloy.user.read_model.repository.seller_details'

    OpenLoyalty\Component\Customer\Domain\ReadModel\CustomerDetailsRepository: '@oloy.user.read_model.repository.customer_details'

    OpenLoyalty\Component\Account\Infrastructure\Provider\AccountDetailsProviderInterface:
        class: OpenLoyalty\Component\Account\Infrastructure\Provider\AccountDetailsProvider
        arguments:
            $accountDetailsRepository: '@oloy.points.account.repository.account_details'

    OpenLoyalty\Component\Customer\Domain\Specification\CustomerPhoneSpecificationInterface: '@OpenLoyalty\Component\Customer\Domain\Specification\CustomerPhoneIsUnique'

    OpenLoyalty\Component\Customer\Domain\Specification\CustomerPhoneIsUnique:
        arguments:
            - '@OpenLoyalty\Component\Customer\Domain\ReadModel\CustomerDetailsRepository'

    OpenLoyalty\Component\Customer\Infrastructure\Provider\CustomerDetailsProvider:
        arguments:
            - '@oloy.user.read_model.repository.customer_details'

    OpenLoyalty\Component\Customer\Infrastructure\Provider\CustomerDetailsProviderInterface: '@OpenLoyalty\Component\Customer\Infrastructure\Provider\CustomerDetailsProvider'

    OpenLoyalty\Component\Customer\Domain\Command\ChangeDeliveryStatusCommandHandler:
        tags:
            - { name: broadway.command_handler }
