OpenLoyalty\Component\Level\Domain\Model\Reward:
  type: embeddable
  fields:
    name:
      type: string
      nullable: true
    value:
      type: decimal
      precision: 14
      scale: 2
      nullable: true
    code:
      type: string
      nullable: true


