OpenLoyalty\Component\Email\Domain\ReadModel\Email:
  exclusion_policy: all
  properties:
    emailId:
      expose: true
      inline: true
    key:
      expose: true
    subject:
      expose: true
    content:
      expose: true
    receiverEmail:
      expose: true
      serialized_name: receiver_email
    senderName:
      expose: true
      serialized_name: sender_name
    senderEmail:
      expose: true
      serialized_name: sender_email
    updatedAt:
      expose: true
