services:

  oloy.utility.customer.details.csv.formatter:
    class: OpenLoyalty\Bundle\UtilityBundle\Service\CustomerDetailsCsvFormatter
    autowire: true
    arguments:
      $segmentedCustomersRepository: '@oloy.segment.read_model.repository.segmented_customers'
      $levelCustomersRepository: '@oloy.user.read_model.repository.customers_belonging_to_one_level'
