OpenLoyalty\Component\Transaction\Domain\ReadModel\TransactionDetails:
  exlusion_policy: all
  properties:
    transactionId:
      expose: true
      inline: true
    customerId:
      expose: true
      inline: true
    posId:
      expose: true
      inline: true
