imports:
    - { resource: services/*.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    OpenLoyalty\Bundle\PointsBundle\Validator\Constraints\CustomerValidator:
        arguments:
            $customerDetailsRepository: '@oloy.user.read_model.repository.customer_details'

    oloy.points.account.command_handler:
        class: OpenLoyalty\Component\Account\Domain\Command\AccountCommandHandler
        arguments:
            - '@oloy.points.account.repository'
            - '@broadway.uuid.generator'
            - '@broadway.event_dispatcher'
        lazy: true
        tags:
            - { name: broadway.command_handler }

    OpenLoyalty\Component\Account\Domain\EventSourcedAccountRepository:
        arguments:
            - '@broadway.event_store'
            - '@broadway.event_handling.event_bus'
            - ['@broadway.metadata_enriching_event_stream_decorator']

    OpenLoyalty\Component\Account\Domain\AccountRepository:
        arguments:
            - '@OpenLoyalty\Component\Account\Domain\EventSourcedAccountRepository'
            - '@broadway.event_store'
            - '@OpenLoyalty\Bundle\CoreBundle\Repository\DBALSnapshotRepository'
            - '@Broadway\Snapshotting\Snapshot\Trigger\EventCountTrigger'

    OpenLoyalty\Component\Account\Domain\ReadModel\PointsTransferDetailsRepository:
        class: 'Broadway\ReadModel\ReadModel'
        factory: ['@oloy.read_model.repository.factory', create]
        arguments:
            - 'oloy.points_transfer_details'
            - 'OpenLoyalty\Component\Account\Domain\ReadModel\PointsTransferDetails'
            - 'OpenLoyalty\Component\Account\Infrastructure\Repository\PointsTransferDetailsElasticsearchRepository'

    oloy.points.account.read_model.projector.point_transfer_details:
        class: 'OpenLoyalty\Component\Account\Domain\ReadModel\PointsTransferDetailsProjector'
        tags:
            - { name: broadway.domain.event_listener }
        arguments:
            $repository: '@oloy.points.account.repository.points_transfer_details'
            $accountRepository: '@oloy.points.account.repository'
            $customerRepository: '@oloy.user.customer.repository'
            $transactionRepository: '@oloy.transaction.repository'
            $posRepository: '@oloy.pos.repository'

    oloy.points.account.repository.account_details:
        class: 'Broadway\ReadModel\ReadModel'
        factory: ['@oloy.read_model.repository.factory', create]
        arguments:
            - 'oloy.account_details'
            - 'OpenLoyalty\Component\Account\Domain\ReadModel\AccountDetails'

    oloy.points.account.read_model.projector.account_details:
        class: 'OpenLoyalty\Component\Account\Domain\ReadModel\AccountDetailsProjector'
        tags:
            - { name: broadway.domain.event_listener }
        arguments:
            - '@oloy.points.account.repository.account_details'

    oloy.points.apply_earning_rule_listener.transaction:
        class: 'OpenLoyalty\Component\Account\Infrastructure\SystemEvent\Listener\ApplyEarningRuleToTransactionListener'
        arguments:
            - '@broadway.command_handling.command_bus'
            - '@oloy.points.account.repository.account_details'
            - '@broadway.uuid.generator'
            - '@OpenLoyalty\Component\EarningRule\Domain\OloyEarningRuleEvaluator'
        tags:
            - { name: broadway.event_listener, event: oloy.transaction.customer_assigned, method: onRegisteredTransaction }

    oloy.points.apply_earning_rule_listener.event:
        class: 'OpenLoyalty\Component\Account\Infrastructure\SystemEvent\Listener\ApplyEarningRuleToEventListener'
        arguments:
            $commandBus: '@broadway.command_handling.command_bus'
            $accountDetailsRepository: '@oloy.points.account.repository.account_details'
            $uuidGenerator: '@broadway.uuid.generator'
            $earningRuleApplier: '@OpenLoyalty\Component\EarningRule\Domain\OloyEarningRuleEvaluator'
            $earningRuleLimitValidator: '@oloy.earning_rule.validator'
        tags:
            - { name: broadway.event_listener, event: oloy.account.created, method: onCustomerRegistered}
            - { name: broadway.event_listener, event: oloy.transaction.customer_first_transaction, method: onFirstTransaction}
            - { name: broadway.event_listener, event: oloy.customer.logged_in, method: onCustomerLogin}
            - { name: broadway.event_listener, event: oloy.customer.newsletter_subscription, method: onNewsletterSubscription }
            - { name: broadway.event_listener, event: oloy.account.custom_event_occurred, method: onCustomEvent }
            - { name: broadway.event_listener, event: oloy.account.custom_event_geo_occurred, method: onCustomGeoEvent }
            - { name: broadway.event_listener, event: oloy.invitation.customer_attached, method: onCustomerAttachedToInvitation }
            - { name: broadway.event_listener, event: oloy.account.custom_event_qrcode_occurred, method: onCustomQrcodeEvent }

    oloy.account.spend_points_on_campaign_listener:
        class: OpenLoyalty\Component\Account\Infrastructure\Event\Listener\SpendPointsOnCampaignListener
        arguments:
            - '@broadway.command_handling.command_bus'
            - '@oloy.points.account.repository.account_details'
            - '@broadway.uuid.generator'
        lazy: true
        tags:
            - { name: broadway.domain.event_listener }

    oloy.account.revoke_points_on_return_transaction_listener:
        class: OpenLoyalty\Component\Account\Infrastructure\Event\Listener\RevokePointsOnReturnTransactionListener
        arguments:
            $transactionRepository: '@oloy.transaction.repository'
            $transfersRepo: '@oloy.points.account.repository.points_transfer_details'
            $accountDetailsRepository: '@oloy.points.account.repository.account_details'
            $commandBus: '@broadway.command_handling.command_bus'
            $uuidGenerator: '@broadway.uuid.generator'
        lazy: true
        tags:
            - { name: broadway.domain.event_listener }

    OpenLoyalty\Component\Account\Infrastructure\Notifier\ExpireLevelNotifierInterface:
        class: OpenLoyalty\Component\Account\Infrastructure\Notifier\ExpireLevelNotifier

    OpenLoyalty\Component\Account\Infrastructure\Notifier\ExpirePointsNotifierInterface:
        class: OpenLoyalty\Component\Account\Infrastructure\Notifier\ExpirePointsNotifier

