imports:
services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    OpenLoyalty\Bundle\PointsBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    OpenLoyalty\Bundle\PointsBundle\Command\PointsTransferImportCommand: ~

    OpenLoyalty\Bundle\PointsBundle\Form\DataTransformer\CustomerDataTransformer: ~
    OpenLoyalty\Bundle\PointsBundle\Form\Type\TransferPointsFormType:
        arguments: ['@OpenLoyalty\Bundle\PointsBundle\Form\DataTransformer\CustomerDataTransformer']
        autowire: false
        tags:
            - { name: form.type }
    OpenLoyalty\Bundle\PointsBundle\Form\Handler\TransferPointsFormHandler:
        arguments:
            $accountDetailsRepo: '@oloy.points.account.repository.account_details'

    OpenLoyalty\Bundle\PointsBundle\Form\Type\TransferPointsByCustomerFormType:
        arguments: ['@OpenLoyalty\Bundle\PointsBundle\Form\DataTransformer\CustomerDataTransformer']
        autowire: false
        tags:
            - { name: form.type }

    OpenLoyalty\Bundle\PointsBundle\Form\Type\AddPointsFormType:
        arguments:
            - '@oloy.user.read_model.repository.customer_details'
        tags:
            - { name: form.type }

    OpenLoyalty\Bundle\PointsBundle\Form\Type\SpendPointsFormType:
        parent: 'OpenLoyalty\Bundle\PointsBundle\Form\Type\AddPointsFormType'
        autoconfigure: false
        autowire: false
        public: true
        tags:
            - { name: form.type }

    OpenLoyalty\Bundle\PointsBundle\Service\PointsTransfersManager:
        public: true
        arguments:
            $commandBus: '@broadway.command_handling.command_bus'
            $pointsTransferDetailsRepository: '@oloy.points.account.repository.points_transfer_details'
            $settingsManager: '@OpenLoyalty\Bundle\SettingsBundle\Service\GeneralSettingsManager'

    oloy.account.points_transfers.serialization_listener:
        class: OpenLoyalty\Bundle\PointsBundle\Event\Listener\PointsTransferSerializationListener
        public: true
        arguments:
            $posRepository: '@oloy.pos.repository'
            $transactionRepository: '@oloy.transaction.repository'
        tags:
            - { name: jms_serializer.event_subscriber }

    oloy.account.points_transfers.param_converter:
        class: OpenLoyalty\Bundle\PointsBundle\ParamConverter\PointsTransferParamConverter
        arguments: ['@oloy.points.account.repository.points_transfer_details']
        tags:
            - { name: request.param_converter, priority: 2, converter: points_transfer_converter }

    oloy.account.listener.available_points_amount_changed:
        class: OpenLoyalty\Bundle\PointsBundle\Event\Listener\AvailablePointsAmountChangedListener
        arguments: ['@oloy.user.email_provider', '@oloy.user.read_model.repository.customer_details']
        tags:
            - { name: broadway.event_listener, method: onChange, event: oloy.account.available_points_amount_changed}

    OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferNodeStreamer: ~

    OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferImportProcessor:
        arguments:
            - "@broadway.command_handling.command_bus"

    OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferXmlImportConverter:
        arguments:
            - "@broadway.uuid.generator"
            - '@OpenLoyalty\Bundle\PointsBundle\Service\PointsTransfersManager'

    OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferXmlImporter:
        calls:
            - [setProcessor, ['@OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferImportProcessor']]
            - [setXmlStreamer, ['@OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferNodeStreamer']]
            - [setConverter, ['@OpenLoyalty\Bundle\PointsBundle\Import\PointsTransferXmlImportConverter']]

    OpenLoyalty\Bundle\PointsBundle\Import\AccountProvider:
        arguments:
            $customerRepository: '@oloy.user.read_model.repository.customer_details'
            $accountRepository: '@oloy.points.account.repository.account_details'
