services:
  oloy.audit.manager:
    class: OpenLoyalty\Bundle\AuditBundle\Service\AuditManager
    arguments:
      - '@broadway.command_handling.command_bus'
      - '@oloy.user.read_model.repository.customer_details'
      - '@security.token_storage'
    tags:
      - { name: broadway.event_listener, event: broadway.command_handling.command_success, method: handleCommand }
