services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OpenLoyalty\Bundle\LevelBundle\Controller\Api\:
    resource: '../../Controller/Api'
    tags: ['controller.service_arguments']

  OpenLoyalty\Bundle\LevelBundle\Service\:
    resource: '../../Service'

  OpenLoyalty\Bundle\LevelBundle\Service\LevelPhotoUploader:
    arguments:
      $filesystem: "@oloy.level.photos_filesystem"

  oloy.level.form_type.reward:
    class: OpenLoyalty\Bundle\LevelBundle\Form\Type\RewardFormType
    tags:
      - { name: form.type }

  oloy.level.form_type.special_reward:
    class: OpenLoyalty\Bundle\LevelBundle\Form\Type\SpecialRewardFormType
    arguments:
      - '@broadway.uuid.generator'
    tags:
      - { name: form.type }

  oloy.level.param_converter:
    class: OpenLoyalty\Bundle\LevelBundle\ParamConverter\LevelParamConverter
    arguments: ['@oloy.level.repository']
    tags:
      - { name: request.param_converter, priority: 2, converter: level_converter }

  oloy.level.photos_filesystem:
    class:     Gaufrette\Filesystem
    factory:   ['@knp_gaufrette.filesystem_map', get]
    arguments: ['campaign_photos']

  oloy.level.validator.image:
    class: OpenLoyalty\Bundle\LevelBundle\Validator\Constraints\ImageValidator
    arguments:
      - '%oloy.level.photos_min_width%'
      - '%oloy.level.photos_min_height%'
    tags:
      - { name: validator.constraint_validator }

  OpenLoyalty\Bundle\LevelBundle\Form\Type\LevelFormType:
    tags:
      - { name: form.type }

  OpenLoyalty\Bundle\LevelBundle\EventListener\LevelSerializationListener:
    public: true
    tags:
      - { name: jms_serializer.event_subscriber }