OpenLoyalty\Component\Segment\Domain\ReadModel\SegmentedCustomers:
  exlusion_policy: ALL
  properties:
    segmentId:
      expose: true
      inline: true
    customerId:
      expose: true
      inline: true
